=== SIMUXXE/TIPSITCourse-Y2324/lezione1.xsd
<?xml version="1.0" encoding="utf-8"?>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
        <xs:element name="myteam">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="member" maxOccurs="6">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="name" type="xs:string"/>
                                <xs:element name="type" type="xs:string"/>
                                <xs:element name="dexNum" type="xs:string"/>
                                <xs:element name="name" type="xs:integer"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:complexTypeZ>
        </xs:element>
    </xs:schema>

=== SIMUXXE/TIPSITCourse-Y2324/Lesson1/lezione1.xml
<?xml version="1.0" encoding="utf-8"?>
<myteam xmlns:xsi="http://www.w3.org/2001/XMLSchema-intance" xsi:noNamespaceSchemaLocation="lezione1.xsd">
    <member> 
        <name>Lugia</name>
        <type>psicoVolante</type>
        <dexNum>#249</dexNum>
        <baseStats>680</baseStats>
    </member>
    <member>
        <name>HisuianArcanine</name>
        <type>fuocoRoccia</type>
        <dexNum>#059</dexNum>
        <baseStats>555</baseStats>
    </member>
        <member>
        <name>Typhlosion</name>
        <type>fuoco</type>
        <dexNum>#157</dexNum>
        <baseStats>534</baseStats>
    </member>
        <member>
        <name>Koraidon</name>
        <type>lottaDrago</type>
        <dexNum>#1007</dexNum>
        <baseStats>670</baseStats>
    </member>
        <member>
        <name>Garchomp</name>
        <type>dragoTerra</type>
        <dexNum>#445</dexNum>
        <baseStats>600</baseStats>
    </member>
    <member>
        <name>Torterra</name>
        <type>erbaTerra</type>
        <dexNum>#389</dexNum>
        <baseStats>525</baseStats>
    </member>
</myteam>
