=== SIMUXXE/TIPSITCourse-Y2324/xml & xsd validated/CompanyOrganization.xsd
<?xml version = "1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Company">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Departement" minOccurs="3" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Employee">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Id" type="xs:string"/>
                <xs:element name="Name" type="xs:string"/>
                <xs:element name="Surname" type="xs:string"/>
                <xs:element name="BirthDate" type="xs:date"/>
                <xs:element name="HireDate" type="xs:date"/>
                <xs:element name="ContractLv" type="xs:integer"/>                
                <xs:element name="Salary" type="xs:integer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Departement">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="DepartementName" type="xs:string"/>
                <xs:element name="Employee" minOccurs="3" maxOccurs="10"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SIMUXXE/TIPSITCourse-Y2324/xml & xsd validated/CompanyOrganization.xml
<?xml version="1.0" encoding="UTF-8"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CompanyOrganization.xsd">
    <Departement>
        <DepartementName>
            ComputerScienze
        </DepartementName>
        <Employee>
            <Id>
                LCR123
            </Id>
            <Name>
                Luca 
            </Name>
            <Surname>
                Rossi 
            </Surname>
            <BirthDate>
                1980-08-22
            </BirthDate>
            <HireDate>
                2000-10-25
            </HireDate>
            <ContractLv>
                5
            </ContractLv>
            <Salary>
                2000
            </Salary>
        </Employee>
        <Employee>
            <Id>
                MBA456
            </Id>
            <Name>
                Martina 
            </Name>
            <Surname>
                Bianchi 
            </Surname>
            <BirthDate>
                1990-03-22
            </BirthDate>
            <HireDate>
                2000-10-25
            </HireDate>
            <ContractLv>
                5
            </ContractLv>
            <Salary>
                2000
            </Salary>
        </Employee>
            <Id>
                MCR789
            </Id>
            <Name>
                Marco 
            </Name>
            <Surname>
                Russo 
            </Surname>
            <BirthDate>
                1988-11-10
            </BirthDate>
            <HireDate>
                2000-10-25
            </HireDate>
            <ContractLv>
                5
            </ContractLv>
            <Salary>
                2000
            </Salary>
        </Employee>
    </Departement>

    <Departement>
        <DepartementName>
            Networking
        </DepartementName>
        <Employee>
            <Id>
                AM123 
            </Id>
            <Name>
                Alessandro    
            </Name>
            <Surname>
                Martini  
            </Surname>
            <BirthDate>
                1995-08-15
            </BirthDate>
            <HireDate>
                2000-10-25
            </HireDate>
            <ContractLv>
                5
            </ContractLv>
            <Salary>
                1300
            </Salary>
        </Employee>
        <Employee>
            <Id>
                VC456 
            </Id>
            <Name>
                Valentina  
            </Name>
            <Surname>
                conti 
            </Surname>
            <BirthDate>
                1990-03-22
            </BirthDate>
            <HireDate>
                2000-10-25
            </HireDate>
            <ContractLv>
                5
            </ContractLv>
            <Salary>
                1300
            </Salary>
        </Employee>
            <Id>
                GR234
            </Id>
            <Name>
                Giovanni  
            </Name>
            <Surname>
                Romano 
            </Surname>
            <BirthDate>
                1997-02-28
            </BirthDate>
            <HireDate>
                2000-10-25
            </HireDate>
            <ContractLv>
                5
            </ContractLv>
            <Salary>
                1300
            </Salary>
        </Employee>
    </Departement>

    <Departement>
        <DepartementName>
            BuisnessManagment
        </DepartementName>
        <Employee>
            <Id>
                AB123  
            </Id>
            <Name>
                Andrea     
            </Name>
            <Surname>
                Bianchi  
            </Surname>
            <BirthDate>
                1990-05-15
            </BirthDate>
            <HireDate>
                2000-10-25
            </HireDate>
            <ContractLv>
                5
            </ContractLv>
            <Salary>
                1000
            </Salary>
        </Employee>
        <Employee>
            <Id>
                VC456 
            </Id>
            <Name>
                Sofia   
            </Name>
            <Surname>
                Esposito 
            </Surname>
            <BirthDate>
                1995-04-10
            </BirthDate>
            <HireDate>
                2000-10-25
            </HireDate>
            <ContractLv>
                5
            </ContractLv>
            <Salary>
                1000
            </Salary>
        </Employee>
            <Id>
                GR234
            </Id>
            <Name>
                Barbascura  
            </Name>
            <Surname>
                X 
            </Surname>
            <BirthDate>
                1993-11-19
            </BirthDate>
            <HireDate>
                2000-10-25
            </HireDate>
            <ContractLv>
                100
            </ContractLv>
            <Salary>
                1000000000
            </Salary>
        </Employee>
    </Departement>
